config/routes.rb
Rails.application.routes.draw do
    
    devise_for :users, :controllers => { :registrations => 'registrations' }
    
    devise_scope :user do
        get 'register', to: 'devise/registrations#new'
        get 'login', to: 'devise/sessions#new'
        delete 'logout', to: 'devise/sessions#destroy'
    end
    
    resources :pricing_plans
    resources :meal_plans do
        collection do
           get 'meals', to: 'meal_plans#meals_json'
       end
    end
    
    resources :meals do
        resources :meal_reviews, except: [:show, :index]
    end
  
    resources :orders
  
    root 'meals#index'
    put 'activate_meal_plan', to: 'meal_plans#set_active'
    
    #get 'meals_json', to: 'meal_plans#meals_json'
    
    get 'plans', to: 'pages#plans'
end

app/models/meal_plan.rb
class MealPlan < ActiveRecord::Base
    
    # Associations
    belongs_to :user
    
    # http://stackoverflow.com/questions/2166613/multiple-foreign-keys-referencing-the-same-table-in-ror
    belongs_to :monday_breakfast_meal, :class_name => "Meal"
    belongs_to :monday_lunch_meal, :class_name => "Meal"
    belongs_to :monday_dinner_meal, :class_name => "Meal"
    
    belongs_to :tuesday_breakfast_meal, :class_name => "Meal"
    belongs_to :tuesday_lunch_meal, :class_name => "Meal"
    belongs_to :tuesday_dinner_meal, :class_name => "Meal"
    
    belongs_to :wednesday_breakfast_meal, :class_name => "Meal"
    belongs_to :wednesday_lunch_meal, :class_name => "Meal"
    belongs_to :wednesday_dinner_meal, :class_name => "Meal"
    
    belongs_to :thursday_breakfast_meal, :class_name => "Meal"
    belongs_to :thursday_lunch_meal, :class_name => "Meal"
    belongs_to :thursday_dinner_meal, :class_name => "Meal"
    
    belongs_to :friday_breakfast_meal, :class_name => "Meal"
    belongs_to :friday_lunch_meal, :class_name => "Meal"
    belongs_to :friday_dinner_meal, :class_name => "Meal"
    
    # Validations
    validates :name, :presence => true
    validates :user, :presence => true
    
end

app/controllers/meal_plans_controller.rb
class MealPlansController < ApplicationController
    
    respond_to :html, :json
    
    before_action :authenticate_user!
    load_and_authorize_resource param_method: :meal_plan_params
    
    before_action :find_meal_plan, only: [:show, :edit, :update, :destroy, :set_active]
    
    def index
        @meal_plans = current_user.meal_plans
    end
    
    def new
        @meal_plan = current_user.meal_plans.build
    end
    
    def create
        @meal_plan = current_user.meal_plans.build(meal_plan_params)
        @meal_plan.save
        
        # Check if the user already has an active plan
        if current_user.active_meal_plan.blank?
            # Set this plan to be active
            current_user.active_meal_plan = @meal_plan
            current_user.save
        end
        
        respond_with @meal_plan, location: -> { meal_plan_path(@meal_plan) }
    end
    
    def edit
    end
    
    def update
        @meal_plan.update(meal_plan_params)
        respond_with @meal_plan, location: -> { meal_plan_path(@meal_plan)}
    end
    
    def destroy
        @meal_plan.destroy
        respond_with @meal_plan, location: -> { meal_plans_path }
    end
    
    def meals_json
        # JSON data for JQuery TokenInput
        @meals_json = Meal.all.where("name LIKE ?", "%#{params[:q]}%")
        respond_with @meals_json.map { |model| {:id => model.id, :name => model.name } } 
    end
    
    def set_active
        current_user.active_meal_plan = @meal_plan
        current_user.save
        
        respond_with @meal_plan, location: -> { meal_plans_path }
    end
    
    private
    
        def find_meal_plan
           @meal_plan = MealPlan.find(params[:id]) 
        end
        
        def meal_plan_params
            params.require(:meal_plan).permit(:name, :user_id,
                :monday_breakfast_meal_id, :monday_lunch_meal_id, :monday_dinner_meal_id,
                :tuesday_breakfast_meal_id, :tuesday_lunch_meal_id, :tuesday_dinner_meal_id,
                :wednesday_breakfast_meal_id, :wednesday_lunch_meal_id, :wednesday_dinner_meal_id,
                :thursday_breakfast_meal_id, :thursday_lunch_meal_id, :thursday_dinner_meal_id,
                :friday_breakfast_meal_id, :friday_lunch_meal_id, :friday_dinner_meal_id
            ) 
        end
    
end

app/helpers/meal_plans_helper.rb
module MealPlansHelper
end

app/views/meal_plans/_form.html.haml
= form_for @meal_plan do |f|
    
    // ERROR MESSAGES
    = render "shared/errors", model: @meal_plan
    
    .form-group
        = f.label :name
        = f.text_field :name, autofocus: true, class: 'form-control'

    %table.table.table-responsive
        %thead
            %tr
                %th
                %th.text-center Monday
                %th.text-center Tuesday
                %th.text-center Wednesday
                %th.text-center Thursday
                %th.text-center Friday
        %tbody
            %tr
                %td
                    %h5
                        %strong Breakfast (8:00am)
                %td.form-group.col-md-2
                    = f.collection_select(:monday_breakfast_meal_id, Meal.all, :id, :name, {:prompt => true}, {:class => 'form-control select2'})
                %td.form-group.col-md-2
                    = f.collection_select(:tuesday_breakfast_meal_id, Meal.all, :id, :name, {:prompt => true}, {:class => 'form-control select2'})
                %td.form-group.col-md-2
                    = f.collection_select(:wednesday_breakfast_meal_id, Meal.all, :id, :name, {:prompt => true}, {:class => 'form-control select2'})
                %td.form-group.col-md-2
                    = f.collection_select(:thursday_breakfast_meal_id, Meal.all, :id, :name, {:prompt => true}, {:class => 'form-control select2'})
                %td.form-group.col-md-2
                    = f.collection_select(:friday_breakfast_meal_id, Meal.all, :id, :name, {:prompt => true}, {:class => 'form-control select2'})
            %tr
                %td
                    %h5
                        %strong Lunch (12:00pm)
                %td.form-group.col-md-2
                    = f.collection_select(:monday_lunch_meal_id, Meal.all, :id, :name, {:prompt => true}, {:class => 'form-control select2'})
                %td.form-group.col-md-2
                    = f.collection_select(:tuesday_lunch_meal_id, Meal.all, :id, :name, {:prompt => true}, {:class => 'form-control select2'})
                %td.form-group.col-md-2
                    = f.collection_select(:wednesday_lunch_meal_id, Meal.all, :id, :name, {:prompt => true}, {:class => 'form-control select2'})
                %td.form-group.col-md-2
                    = f.collection_select(:thursday_lunch_meal_id, Meal.all, :id, :name, {:prompt => true}, {:class => 'form-control select2'})
                %td.form-group.col-md-2
                    = f.collection_select(:friday_lunch_meal_id, Meal.all, :id, :name, {:prompt => true}, {:class => 'form-control select2'})
            %tr
                %td
                    %h5
                        %strong Dinner (6:00pm)
                %td.form-group.col-md-2
                    = f.collection_select(:monday_dinner_meal_id, Meal.all, :id, :name, {:prompt => true}, {:class => 'form-control select2'})
                %td.form-group.col-md-2
                    = f.collection_select(:tuesday_dinner_meal_id, Meal.all, :id, :name, {:prompt => true}, {:class => 'form-control select2'})
                %td.form-group.col-md-2
                    = f.collection_select(:wednesday_dinner_meal_id, Meal.all, :id, :name, {:prompt => true}, {:class => 'form-control select2'})
                %td.form-group.col-md-2
                    = f.collection_select(:thursday_dinner_meal_id, Meal.all, :id, :name, {:prompt => true}, {:class => 'form-control select2'})
                %td.form-group.col-md-2
                    = f.collection_select(:friday_dinner_meal_id, Meal.all, :id, :name, {:prompt => true}, {:class => 'form-control select2'})
                    
    .form-group
        = f.submit ( f.object.new_record? ? "Create Meal Plan" : "Save Changes"), class: 'btn btn-success', data: { disable_with: "Processing Your Meal Plan..." }
        = link_to 'Cancel', meal_plans_path, class: 'btn btn-default'

app/views/meal_plans/edit.html.haml
.page-header
    %h2 Edit Meal Plan
    
= render 'form'

%hr

= link_to :back do
    %i.fa.fa-arrow-left
    Back

app/views/meal_plans/index.html.haml
.page-header
    %h2
        %i.fa.fa-cutlery
        My Meal Plans
        
        .pull-right
            = link_to new_meal_plan_path, class: 'btn btn-default btn-xs' do
                %i.fa.fa-plus
                New Meal Plan
        
%ul.list-group
    - @meal_plans.each do |plan|
        %li.list-group-item{ class: "#{current_user.active_meal_plan == plan ? 'list-group-item-success' : ''}"}
            %h4
                = link_to plan.name, plan
            
                .pull-right
                    .btn-toolbar
                        .btn-group.btn-group-sm
                            - if current_user.active_meal_plan != plan
                                = form_tag({controller: "meal_plans", action: "set_active"}, method: "put") do
                                    = hidden_field_tag(:id, plan.id)
                                    = submit_tag 'Activate', class: 'btn btn-warning btn-sm'
                        .btn-group.btn-group-sm
                            - if can? :edit, plan
                                = link_to [:edit, plan], class: 'btn btn-default' do
                                    %i.fa.fa-pencil
                        
                            - if can? :destroy, plan
                                = link_to plan, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do
                                    %i.fa.fa-trash
                                    

app/views/meal_plans/new.html.haml
.page-header
    %h2 New Meal Plan
    
= render 'form'

%hr

= link_to meal_plans_path do
    %i.fa.fa-arrow-left
    Back

app/views/meal_plans/show.html.haml
.page-header
    %h2
        = @meal_plan.name
        - if current_user.active_meal_plan == @meal_plan
            %i.fa.fa-check.text-success{ "data-toggle": "tooltip", "data-placement": "right", title: "This is your current active meal plan" }
        
        .pull-right
            .btn-group.btn-group-xs
                - if can? :edit, @meal_plan
                    = link_to [:edit, @meal_plan], class: 'btn btn-default' do
                        %i.fa.fa-pencil
                        Edit
            
                - if can? :destroy, @meal_plan
                    = link_to @meal_plan, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do
                        %i.fa.fa-trash
                        Delete
    
%table.table.table-responsive
    %thead
        %tr
            %th
            %th.text-center Monday
            %th.text-center Tuesday
            %th.text-center Wednesday
            %th.text-center Thursday
            %th.text-center Friday
    %tbody
        / BREAKFAST
        %tr
            %td
                %h5
                    %strong Breakfast (8:00am)
            %td.col-md-2
                - unless @meal_plan.monday_breakfast_meal.blank?
                    = link_to (image_tag (@meal_plan.monday_breakfast_meal.image.to_s), class: 'img-rounded img-responsive'), @meal_plan.monday_breakfast_meal
            %td.col-md-2
                - unless @meal_plan.tuesday_breakfast_meal.blank?
                    = link_to (image_tag (@meal_plan.tuesday_breakfast_meal.image.to_s), class: 'img-rounded img-responsive'), @meal_plan.tuesday_breakfast_meal
            %td.col-md-2
                - unless @meal_plan.wednesday_breakfast_meal.blank?
                    = link_to (image_tag (@meal_plan.wednesday_breakfast_meal.image.to_s), class: 'img-rounded img-responsive'), @meal_plan.wednesday_breakfast_meal
            %td.col-md-2
                - unless @meal_plan.thursday_breakfast_meal.blank?
                    = link_to (image_tag (@meal_plan.thursday_breakfast_meal.image.to_s), class: 'img-rounded img-responsive'), @meal_plan.thursday_breakfast_meal
            %td.col-md-2
                - unless @meal_plan.friday_breakfast_meal.blank?
                    = link_to (image_tag (@meal_plan.friday_breakfast_meal.image.to_s), class: 'img-rounded img-responsive'), @meal_plan.friday_breakfast_meal
        / LUNCH
        %tr
            %td
                %h5
                    %strong Lunch (12:00pm)
            %td.col-md-2
                - unless @meal_plan.monday_lunch_meal.blank?
                    = link_to (image_tag (@meal_plan.monday_lunch_meal.image.to_s), class: 'img-rounded img-responsive'), @meal_plan.monday_lunch_meal
            %td.col-md-2
                - unless @meal_plan.tuesday_lunch_meal.blank?
                    = link_to (image_tag (@meal_plan.tuesday_lunch_meal.image.to_s), class: 'img-rounded img-responsive'), @meal_plan.tuesday_lunch_meal
            %td.col-md-2
                - unless @meal_plan.wednesday_lunch_meal.blank?
                    = link_to (image_tag (@meal_plan.wednesday_lunch_meal.image.to_s), class: 'img-rounded img-responsive'), @meal_plan.wednesday_lunch_meal
            %td.col-md-2
                - unless @meal_plan.thursday_lunch_meal.blank?
                    = link_to (image_tag (@meal_plan.thursday_lunch_meal.image.to_s), class: 'img-rounded img-responsive'), @meal_plan.thursday_lunch_meal
            %td.col-md-2
                - unless @meal_plan.friday_lunch_meal.blank?
                    = link_to (image_tag (@meal_plan.friday_lunch_meal.image.to_s), class: 'img-rounded img-responsive'), @meal_plan.friday_lunch_meal
        /DINNER
        %tr
            %td
                %h5
                    %strong Dinner (6:00pm)
            %td.col-md-2
                - unless @meal_plan.monday_dinner_meal.blank?
                    = link_to (image_tag (@meal_plan.monday_dinner_meal.image.to_s), class: 'img-rounded img-responsive'), @meal_plan.monday_dinner_meal
            %td.col-md-2
                - unless @meal_plan.tuesday_dinner_meal.blank?
                    = link_to (image_tag (@meal_plan.tuesday_dinner_meal.image.to_s), class: 'img-rounded img-responsive'), @meal_plan.tuesday_dinner_meal
            %td.col-md-2
                - unless @meal_plan.wednesday_dinner_meal.blank?
                    = link_to (image_tag (@meal_plan.wednesday_dinner_meal.image.to_s), class: 'img-rounded img-responsive'), @meal_plan.wednesday_dinner_meal
            %td.col-md-2
                - unless @meal_plan.thursday_dinner_meal.blank?
                    = link_to (image_tag (@meal_plan.thursday_dinner_meal.image.to_s), class: 'img-rounded img-responsive'), @meal_plan.thursday_dinner_meal
            %td.col-md-2
                - unless @meal_plan.friday_dinner_meal.blank?
                    = link_to (image_tag (@meal_plan.friday_dinner_meal.image.to_s), class: 'img-rounded img-responsive'), @meal_plan.friday_dinner_meal
            
%hr

= link_to meal_plans_path do
    %i.fa.fa-arrow-left
    Back
    
:javascript
    $('[data-toggle="tooltip"]').tooltip();