config/routes.rb
Rails.application.routes.draw do
    
    devise_for :users, :controllers => { :registrations => 'registrations' }
    
    devise_scope :user do
        get 'register', to: 'devise/registrations#new'
        get 'login', to: 'devise/sessions#new'
        delete 'logout', to: 'devise/sessions#destroy'
    end
    
    resources :pricing_plans
    resources :meal_plans do
        collection do
           get 'meals', to: 'meal_plans#meals_json'
       end
    end
    
    resources :meals do
        resources :meal_reviews, except: [:show, :index]
    end
  
    resources :orders
  
    root 'meals#index'
    put 'activate_meal_plan', to: 'meal_plans#set_active'
    
    #get 'meals_json', to: 'meal_plans#meals_json'
    
    get 'plans', to: 'pages#plans'
end

app/views/pages/plans/_basic.html.haml
// PLAN BASICO
.panel.panel-default
    .panel-heading
        %h2.text-center 
            = @basic_plan.name
            %br
            %small
                = "$#{@basic_plan.price} / month"
            
    %ul.list-group
        %li.list-group-item 
            %strong 3
            Meals per day,
            %strong 3
            times per week
            %span.fa.fa-check.text-success.pull-right
    
        %li.list-group-item 
            Delivered right to your home.
            %span.fa.fa-check.text-success.pull-right
            
        %li.list-group-item 
            Tons of available healthy meals
            %span.fa.fa-check.text-success.pull-right
            
        %li.list-group-item 
            Change your meals at any time.
            %span.fa.fa-check.text-success.pull-right
            
    .panel-footer
        .text-center
            = link_to 'Select Plan', register_path(plan: @basic_plan.name), class: 'btn btn-success btn-lg'