config/routes.rb
Rails.application.routes.draw do
    
    devise_for :users, :controllers => { :registrations => 'registrations' }
    
    devise_scope :user do
        get 'register', to: 'devise/registrations#new'
        get 'login', to: 'devise/sessions#new'
        delete 'logout', to: 'devise/sessions#destroy'
    end
    
    resources :pricing_plans
    resources :meal_plans do
        collection do
           get 'meals', to: 'meal_plans#meals_json'
       end
    end
    
    resources :meals do
        resources :meal_reviews, except: [:show, :index]
    end
  
    resources :orders
  
    root 'meals#index'
    put 'activate_meal_plan', to: 'meal_plans#set_active'
    
    #get 'meals_json', to: 'meal_plans#meals_json'
    
    get 'plans', to: 'pages#plans'
end

app/models/pricing_plan.rb
class PricingPlan < ActiveRecord::Base
    
    # Validations
    validates :name, :presence => true
    validates :price, :presence => true
    validates :state, :presence => true
    
    # Associations
    has_many :users
end

app/controllers/pricing_plans_controller.rb
class PricingPlansController < ApplicationController
    
    respond_to :html
    
    before_action :authenticate_user!
    load_and_authorize_resource param_method: :plan_params
    
    before_action :find_plan, only: [:show, :edit, :update, :destroy]
    
    def index
        @plans = PricingPlan.all.order('created_at DESC')
    end
    
    def new
        @plan = PricingPlan.new
    end
    
    def create
        @plan = PricingPlan.create(plan_params)
        respond_with @plan, location: -> { pricing_plans_path }    
    end
    
    def edit
    end
    
    def update
       @plan.update(plan_params)
       respond_with @plan, location: -> { pricing_plans_path }
    end
    
    def destroy
       @plan.destroy
       respond_with @plan, location: -> { pricing_plans_path }
    end
    
    private
    
        def find_plan
            @plan = PricingPlan.find(params[:id])
        end
    
        def plan_params
           params.require(:pricing_plan).permit(:name, :price, :state, :stripe_name) 
        end
end

app/helpers/pricing_plans_helper.rb
module PricingPlansHelper
end

app/views/pricing_plans/_form.html.haml
= form_for @plan do |f|
    .row
        .col-md-4
            .form-group
                = f.label :name
                = f.text_field :name, autofocus: true, class: 'form-control'
        
        .col-md-4
            .form-group
                = f.label :price
                = f.text_field :price, class: 'form-control'
    
        .col-md-4
            .form-group
                = f.label :state
                %br
                .btn-group{ "data-toggle": "buttons"}
                    %label.btn.btn-default.active
                        = f.radio_button :state, 'active', :checked => true
                        %span.fa.fa-check
                        Active
                    %label.btn.btn-default
                        = f.radio_button :state, 'inactive'
                        %span.fa.fa-times
                        Inactive
        
        .form-group
            .col-md-12
                = f.submit ( f.object.new_record? ? "Add New Plan" : "Save Changes"), class: 'btn btn-success'
                = link_to 'Cancel', :back, class: 'btn btn-default'
            

app/views/pricing_plans/edit.html.haml
.page-header
    %h2 Edit Pricing Plan
    
= render 'form'

%hr

= link_to pricing_plans_path do
    %i.fa.fa-arrow-left
    Back

app/views/pricing_plans/index.html.haml
.page-header
    %h2 Pricing Plans
    
.row
    .col-md-12
        .pull-right
            = link_to new_pricing_plan_path, class: 'btn btn-default btn-xs' do
                %i.fa.fa-plus
                New Pricing Plan
                
.row
    .col-md-12
    
        %table.table.table-responsive.table-striped.table-hover
            %thead
                %tr
                    %th #
                    %th Name
                    %th Monthly Price
                    %th State
                    %th
            %tbody
                - @plans.each_with_index do |plan, index|
                    %tr
                        %td= index + 1
                        %td= plan.name
                        %td= plan.price
                        %td= plan.state
                        %td
                            .btn-group.btn-group-xs
                                - if can? :edit, plan
                                    = link_to [:edit, plan], class: 'btn btn-default' do
                                        %i.fa.fa-pencil
                                - if can? :destroy, plan
                                    = link_to plan, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do
                                        %i.fa.fa-trash
            

app/views/pricing_plans/new.html.haml
.page-header
    %h2 New Pricing Plan

= render 'form'

%hr

= link_to pricing_plans_path do
    %i.fa.fa-arrow-left
    Back