config/routes.rb
Rails.application.routes.draw do
    
    devise_for :users, :controllers => { :registrations => 'registrations' }
    
    devise_scope :user do
        get 'register', to: 'devise/registrations#new'
        get 'login', to: 'devise/sessions#new'
        delete 'logout', to: 'devise/sessions#destroy'
    end
    
    resources :pricing_plans
    resources :meal_plans do
        collection do
           get 'meals', to: 'meal_plans#meals_json'
       end
    end
    
    resources :meals do
        resources :meal_reviews, except: [:show, :index]
    end
  
    resources :orders
  
    root 'meals#index'
    put 'activate_meal_plan', to: 'meal_plans#set_active'
    
    #get 'meals_json', to: 'meal_plans#meals_json'
    
    get 'plans', to: 'pages#plans'
end

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default{role: "navigation"}
    / Brand and toggle get grouped for better mobile display
    .navbar-header
        %button.navbar-toggle{"data-target" => ".navbar-ex1-collapse", "data-toggle" => "collapse", type: "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
        = link_to root_path, class: 'navbar-brand' do
            /= image_tag 'hourglass_icon24.png'
            %big.app-title
                %strong= "#{APP_NAME}"
    
    / Collect the nav links, forms, and other content for toggling
    .collapse.navbar-collapse.navbar-ex1-collapse
        %ul.nav.navbar-nav
            
            
        %ul.nav.navbar-nav.navbar-right
            - if user_signed_in?
                %li.dropdown
                    %a{ :class => 'dropdown-toggle', "data-toggle" => 'dropdown', :role => 'button', "aria-expanded" => false }
                        %strong= current_user.email 
                        %span.caret
                    %ul{:class => 'dropdown-menu', :role => 'menu' }
                        - if current_user.has_role? :admin
                            %li.dropdown-header Administration
                            %li
                                = link_to pricing_plans_path do
                                    %i.fa.fa-credit-card
                                    Pricing Plans
                            
                            %li
                                = link_to orders_path do
                                    %i.fa.fa-file-text-o
                                    Orders
                        
                            %li
                                = link_to [:new, :meal] do
                                    %i.fa.fa-plus
                                    Create New Meal
                                    
                            %li.divider
                        
                        %li.dropdown-header Meal Plans
                        - if can? :create, MealPlan
                            %li
                                = link_to meal_plans_path do
                                    %i.fa.fa-cutlery
                                    My Meal Plans
                        
                        %li.divider
                        
                        %li
                            = link_to logout_path, method: :delete do
                                %i.fa.fa-sign-out
                                Logout
            - else
                %li= link_to 'Pricing Plans', plans_path
                %li= link_to 'Log In', login_path
                
          
        / /.navbar-collapse

app/views/layouts/application.html.haml
!!! 5

%html
%head
    %title 
        = "#{APP_NAME}"
    
    / Application Assets
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    
    / Bootstrap
    = stylesheet_link_tag "https://bootswatch.com/#{BOOTSTRAP_THEME}/bootstrap.min.css"
    = javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js', 'data-turbolinks-track' => false
    
    / Font Awesome
    = stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"

    / Dancing Script Font
    = stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Dancing+Script'

    = csrf_meta_tags
    
    /= favicon_link_tag 'favicon.ico'
    
%body
    

    .container
        .row
            .col-md-11.col-md-offset-0.5
                // NAVBAR
                = render 'layouts/navbar'
            
                // ALERTS
                = render 'shared/alerts'

                .panel.panel-default
                    .panel-body
                        // CONTENT
                        = yield
        
                // FOOTER
                /= render 'layouts/footer'

app/views/layouts/registrations.html.haml
!!! 5

%html
%head
    %title= "#{APP_NAME}"
    
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    
    / Bootstrap
    = stylesheet_link_tag "https://bootswatch.com/#{BOOTSTRAP_THEME}/bootstrap.min.css"
    
    / Font Awesome
    = stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"

    = csrf_meta_tags
    
    /= favicon_link_tag 'favicon.ico'
    
%body

    .container
        .row
            .col-md-8.col-md-offset-2
                %h1
                // CONTENT
                .panel.panel-default
                    .panel-body
                        
                        = yield
        
                

app/views/layouts/sessions.html.haml
!!! 5

%html
%head
    %title= "#{APP_NAME}"
    
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    
    = stylesheet_link_tag "https://bootswatch.com/#{BOOTSTRAP_THEME}/bootstrap.min.css"
    
    = stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"
    
    = csrf_meta_tags
    
    /= favicon_link_tag 'favicon.ico'
    
%body
    .container
        = yield

        
                